server:
  port: 9000

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: YOUR_GOOGLE_CLIENT_ID
#            client-secret: YOUR_GOOGLE_CLIENT_SECRET
#            scope:
#              - profile
#              - email
