server:
  port: 8080

spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**

# Cấu hình Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
